### PR TITLE
Dev/v1

### PR DESCRIPTION
**Pull request by Mishalabdullah**
This is the version 1 of the website and this is using astro framework and tailwind.

### CODE REVIEW

**Comment by joicemjoseph** [comment]
Hello,
Welcome to the osm community and Thank you very much for your contributions. :)

Can you brief the changes ?
Would  be great if you can add couple of screenshots of the changes as well.

**Comment by asdofindia** [comment]
Hi @Mishalabdullah, thanks and welcome, like Joice said. I think what you can do is to avoid committing the generated files and the node modules and all of that. Commit only the source branch of astro and we can use github actions to generate the output. https://docs.astro.build/en/guides/deploy/github/

That'll make this easier to review, merge, maintain, etc.

**Comment by Mishalabdullah** [comment]
Hello, @joicemjoseph  I have created a new repository and built the website from scratch. I have also deployed in on vercel so you can view all the site using the link below.
[https://osmkerala.vercel.app/](https://osmkerala.vercel.app/)

when i was creating the PR i have just copied the files from my repo and into the osmWebsite repo.

initial repo :- [https://github.com/Mishalabdullah/osmkerala](https://github.com/Mishalabdullah/osmkerala)

@asdofindia point notted..

**Comment by joicemjoseph** [comment]
@Mishalabdullah please let me know once you want a review.

**Comment by Mishalabdullah** [comment]
I think I have made all the necessary changes as the generated files are required by GitHub I have only removed the node_modules directory. @joicemjoseph 
image

**Comment by Mishalabdullah** [comment]
@joicemjoseph is there any more changes that need to be made ??

**Comment by asdofindia** [comment]
Hi @Mishalabdullah - while Joice responds, I will respond with how github actions work here (and why you can remove more than just node_modules).

withastro/action@v1 action will not just build astro, but also as the last step upload the artifacts to pages https://github.com/withastro/action/blob/f122c0232093b3504e4c841a46c2eebd07c47392/action.yml#L96

When that is done, deploy-pages action can directly take the artifacts from the workflow https://github.com/actions/deploy-pages#usage

Therefore, you don't have to commit generated files.

**Comment by joicemjoseph** [comment]
> while Joice responds

I was waiting for a confirmation on the content by @arkarjun

**Comment by Mishalabdullah** [comment]
Closing this pr in favor of migrate to astro #15 .

**Pull request closed without merging**
